-- liquibase formatted sql

-- changeset salikhdev:1765807510536-1
CREATE SEQUENCE IF NOT EXISTS size_seq START WITH 1 INCREMENT BY 50;

-- changeset salikhdev:1765807510536-2
CREATE TABLE _user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255),
    role         SMALLINT                                NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    balance      DECIMAL                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

-- changeset salikhdev:1765807510536-3
CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    image_url  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset salikhdev:1765807510536-4
CREATE TABLE color
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    color_tag  VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_color PRIMARY KEY (id)
);

-- changeset salikhdev:1765807510536-5
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    price       DECIMAL                                 NOT NULL,
    color_id    BIGINT                                  NOT NULL,
    category_id BIGINT                                  NOT NULL,
    size_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset salikhdev:1765807510536-6
CREATE TABLE size
(
    id         BIGINT                      NOT NULL,
    name       VARCHAR(255)                NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_size PRIMARY KEY (id)
);

-- changeset salikhdev:1765807510536-7
ALTER TABLE _user
    ADD CONSTRAINT uc__user_phone_number UNIQUE (phone_number);

-- changeset salikhdev:1765807510536-8
ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

-- changeset salikhdev:1765807510536-9
ALTER TABLE color
    ADD CONSTRAINT uc_color_color_tag UNIQUE (color_tag);

-- changeset salikhdev:1765807510536-10
ALTER TABLE color
    ADD CONSTRAINT uc_color_name UNIQUE (name);

-- changeset salikhdev:1765807510536-11
ALTER TABLE size
    ADD CONSTRAINT uc_size_name UNIQUE (name);

-- changeset salikhdev:1765807510536-12
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset salikhdev:1765807510536-13
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_COLOR FOREIGN KEY (color_id) REFERENCES color (id);

-- changeset salikhdev:1765807510536-14
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_SIZE FOREIGN KEY (size_id) REFERENCES size (id);

