-- liquibase formatted sql

-- changeset salikhdev:1766148087088-1
CREATE TABLE _user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255),
    role         SMALLINT                                NOT NULL,
    status       SMALLINT                                NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    balance      DECIMAL                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

-- changeset salikhdev:1766148087088-2
CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    image_url  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset salikhdev:1766148087088-3
CREATE TABLE color
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    color_tag  VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_color PRIMARY KEY (id)
);

-- changeset salikhdev:1766148087088-4
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    price       DECIMAL                                 NOT NULL,
    color_id    BIGINT,
    category_id BIGINT,
    size_id     BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset salikhdev:1766148087088-5
CREATE TABLE size
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_size PRIMARY KEY (id)
);

-- changeset salikhdev:1766148087088-6
ALTER TABLE _user
    ADD CONSTRAINT uc__user_phone_number UNIQUE (phone_number);

-- changeset salikhdev:1766148087088-7
ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

-- changeset salikhdev:1766148087088-8
ALTER TABLE color
    ADD CONSTRAINT uc_color_color_tag UNIQUE (color_tag);

-- changeset salikhdev:1766148087088-9
ALTER TABLE color
    ADD CONSTRAINT uc_color_name UNIQUE (name);

-- changeset salikhdev:1766148087088-10
ALTER TABLE size
    ADD CONSTRAINT uc_size_name UNIQUE (name);

-- changeset salikhdev:1766148087088-11
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL;

-- changeset salikhdev:1766148087088-12
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_COLOR FOREIGN KEY (color_id) REFERENCES color (id) ON DELETE SET NULL;

-- changeset salikhdev:1766148087088-13
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_SIZE FOREIGN KEY (size_id) REFERENCES size (id) ON DELETE SET NULL;

