-- liquibase formatted sql

-- changeset salikhdev:1767618071150-1
CREATE TABLE _user
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone_number VARCHAR(255)                            NOT NULL,
    first_name   VARCHAR(255)                            NOT NULL,
    last_name    VARCHAR(255),
    role         SMALLINT                                NOT NULL,
    status       SMALLINT                                NOT NULL,
    password     VARCHAR(255)                            NOT NULL,
    avatar_url   VARCHAR(255),
    is_active    BOOLEAN                                 NOT NULL,
    balance      DECIMAL                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-2
CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    image_url  VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-3
CREATE TABLE color
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    color_tag  VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_color PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-4
CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    product_id  BIGINT                                  NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    quantity    BIGINT                                  NOT NULL,
    total_price DECIMAL                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-5
CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    price       DECIMAL                                 NOT NULL,
    image_url   VARCHAR(255),
    quantity    BIGINT                                  NOT NULL,
    color_id    BIGINT,
    category_id BIGINT,
    size_id     BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-6
CREATE TABLE resource
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_name VARCHAR(255),
    key           VARCHAR(255),
    size          BIGINT,
    content_type  VARCHAR(255),
    status        VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    passive_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_resource PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-7
CREATE TABLE size
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_size PRIMARY KEY (id)
);

-- changeset salikhdev:1767618071150-8
ALTER TABLE _user
    ADD CONSTRAINT uc__user_phone_number UNIQUE (phone_number);

-- changeset salikhdev:1767618071150-9
ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

-- changeset salikhdev:1767618071150-10
ALTER TABLE color
    ADD CONSTRAINT uc_color_color_tag UNIQUE (color_tag);

-- changeset salikhdev:1767618071150-11
ALTER TABLE color
    ADD CONSTRAINT uc_color_name UNIQUE (name);

-- changeset salikhdev:1767618071150-12
ALTER TABLE size
    ADD CONSTRAINT uc_size_name UNIQUE (name);

-- changeset salikhdev:1767618071150-13
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

-- changeset salikhdev:1767618071150-14
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES _user (id);

-- changeset salikhdev:1767618071150-15
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

-- changeset salikhdev:1767618071150-16
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_COLOR FOREIGN KEY (color_id) REFERENCES color (id);

-- changeset salikhdev:1767618071150-17
ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_SIZE FOREIGN KEY (size_id) REFERENCES size (id);

